# Generated by Django 5.2.8 on 2025-12-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_specialization_doctorprofile_patientprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='doctor_pics/default.jpg', null=True, upload_to='doctor_pics/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('general', 'General'), ('pediatrician', 'Pediatrician'), ('ob_gyn', 'Obstetrics and Gynaecology'), ('orthopedician', 'Orthopedician'), ('ent', 'ENT'), ('ophthalmologist', 'Ophthalmologist'), ('dentist', 'Dentist')], default='general', max_length=50),
        ),
    ]
