# Generated by Django 5.2.8 on 2025-12-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_doctorprofile_cases_to_be_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
