# Generated by Django 5.2.8 on 2025-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
