# Generated by Django 5.2.8 on 2025-12-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_generalmedicalquestion_medicalhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='medical_history',
            new_name='medical_notes',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='doctor',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='users.patientprofile'),
        ),
    ]
