# Generated by Django 5.2.8 on 2025-12-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_medical_history_patientprofile_medical_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_notes',
        ),
    ]
