# Generated by Django 5.2.8 on 2025-12-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_patientprofile_medical_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_histories', to='users.doctorprofile'),
        ),
    ]
