# Generated by Django 5.2.8 on 2025-12-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_medicalhistory_last_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctormessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_doctor_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_doctor_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
