# Generated by Django 5.2.8 on 2025-12-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_doctormessage_options_doctormessage_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctormessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctormessage',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='doctormessage',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.doctorprofile'),
        ),
    ]
