# Generated by Django 5.2.8 on 2025-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_doctormessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormessage',
            name='from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
