# Generated by Django 5.2.8 on 2025-12-26 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_doctormessage_from_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctormessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='doctormessage',
            name='from_admin',
        ),
        migrations.AlterField(
            model_name='doctormessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_doctor_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
